name: Deploy Frontend to Firebase Hosting

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**" # Only trigger when frontend files change

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Upgrade to v4 to fix the Node deprecation warnings
      - uses: actions/checkout@v4

      - name: Install Dependencies and Build
        # This line forces the runner to step into your frontend folder
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting
        # Upgrade to v3 to stay up to date
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GARNE_POHLUPAK }}"
          channelId: live
          # Tell Firebase where to find the target project configurations
          entryPoint: ./frontend
          projectId: garne-pohlupak
